---
- hosts: web
  sudo: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql

  tasks:
    - name: Install mysql client
      yum: name=mysql state=installed

    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent
