---
- hosts: database
  sudo: yes

  vars_files:
    - vars.yml

  #pre_tasks:
  #  - name: Create dynamic MySQL variables.
  #  set_fact:
  #      # mysql_replication_master: "{{ groups['a4d.lamp.db.1'][0] }}"

  roles:
    - geerlingguy.firewall
    - geerlingguy.mysql
